version: 2.1

commands:
  prepare:
    steps:
      - checkout

jobs:
  php_7_4:
    docker:
      - image: circleci/php:7.4
    steps:
      - prepare
  php_8_0:
    docker:
      - image: circleci/php:8.0
    steps:
      - prepare

workflows:
  test-php-versions:
    jobs:
      - php_7_4
      - php_8_0
